# 线上配置文件
# EL PSY CONGGROO
server:
  port: 8222
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.155.98.29:3306/yubi
    username: root
    password: 123456
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 10000
#    database: 0
#    host: 139.155.98.29
#    port: 6379
#    timeout: 10000
#    password: 123456
#    username: default
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    password: SjXCaXXM
    username: admin
#    host: 139.155.98.29
#    port: 5672
#    password: admin
#    username: SjXCaXXM
  # Elasticsearch 配置
  # todo 需替换配置
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）